// Motor adaptativo para concursos: repetição espaçada, diagnóstico e recomendação.
(()=>{const K='sefaz-hipotetico-adaptive-v21',H='sefaz-hipotetico-attempt-history-v25',DAY=86400000,steps=[1,3,7,14,30];
function data(){try{return Object.assign({reviews:{}},JSON.parse(localStorage.getItem(K)||'{}'))}catch(_){return{reviews:{}}}}
function save(d){localStorage.setItem(K,JSON.stringify(d))} function history(){try{return JSON.parse(localStorage.getItem(H)||'[]')}catch(_){return[]}} window.recordAttempt=(id,v,correct,at)=>{const h=history();h.push({id:String(id),v:!!v,correct:!!correct,at:at||Date.now()});if(h.length>50000)h.splice(0,h.length-50000);localStorage.setItem(H,JSON.stringify(h))};
function subj(q){return q.s||q.subject||'Sem matéria'} function topic(q){return q.t||q.topic||'Geral'}
window.addEventListener('cycle-answer',e=>{const id=String(e.detail?.id??'');if(!id)return;const d=data(),r=d.reviews[id]||{level:0,hits:0,misses:0};if(e.detail?.correct){r.hits++;r.level=Math.min(steps.length-1,r.level+1)}else{r.misses++;r.level=0}r.last=Date.now();r.due=r.last+steps[r.level]*DAY;d.reviews[id]=r;save(d);setTimeout(draw,20)});
function metrics(){const st=window.state(),by={},topics={};for(const q of window.Q||[]){const a=st.answers[String(q.id)];if(!a)continue;const s=subj(q),t=s+' • '+topic(q);for(const [obj,k] of [[by,s],[topics,t]]){obj[k]??={n:0,ok:0};obj[k].n++;if(a.correct)obj[k].ok++}}return{by,topics}}
function pct(x){return x.n?Math.round(x.ok/x.n*100):0}
function level(p,n){if(!n)return'Não estudado';if(n<5)return'Amostra inicial';if(p<60)return'Fraco';if(p<80)return'Em desenvolvimento';return'Consolidado'} function bar(p){return '<div style="height:7px;background:#061a33;border-radius:9px;overflow:hidden;margin-top:6px"><div style="height:100%;width:'+p+'%;background:currentColor"></div></div>'}
function readiness(){const h=history(),now=Date.now();if(!h.length)return{score:0,label:'Sem dados',ret:0,coverage:0};const recent=h.filter(x=>now-x.at<=30*DAY),delayed=recent.filter(x=>now-x.at>=DAY),ok=a=>a.length?a.filter(x=>x.correct).length/a.length:0,ret=Math.round(ok(delayed.length?delayed:recent)*100),unique=new Set(recent.map(x=>x.id)).size,coverage=Math.min(100,Math.round(unique/8250*100)),d=data(),rv=Object.values(d.reviews),mature=rv.length?rv.filter(x=>x.level>=2&&x.hits>x.misses).length/rv.length:0,score=Math.round(ret*.60+coverage*.15+mature*100*.25);return{score,label:score>=80?'Alta':score>=65?'Boa':score>=45?'Em construção':'Baixa',ret,coverage}}
window.examReadiness=readiness;
function readiness(){const h=history(),d=data(),now=Date.now();if(!h.length)return{score:0,label:'Sem dados',ret:0,coverage:0,attempts:0};const recent=h.filter(x=>now-x.at<=30*DAY),delayed=recent.filter(x=>now-x.at>=DAY),ret=delayed.length?Math.round(delayed.filter(x=>x.correct).length/delayed.length*100):Math.round(recent.filter(x=>x.correct).length/recent.length*100),unique=new Set(h.map(x=>x.id)).size,coverage=Math.min(100,Math.round(unique/8250*100)),due=Object.values(d.reviews).filter(r=>r.due<=now).length,reinc={};for(const x of h)if(!x.correct)reinc[x.id]=(reinc[x.id]||0)+1;const repeat=Object.values(reinc).filter(n=>n>=2).length,penalty=Math.min(25,due/10)+Math.min(20,repeat/5),score=Math.max(0,Math.min(100,Math.round(ret*.65+coverage*.35-penalty)));return{score,label:score>=85?'Alta':score>=70?'Boa':score>=50?'Em desenvolvimento':'Baixa',ret,coverage,attempts:h.length,due,repeat}} window.examReadiness=readiness;
function weakest(){const {by}=metrics(),a=Object.entries(by).map(([s,x])=>({s,p:pct(x),n:x.n})).filter(x=>x.n>=3).sort((a,b)=>a.p-b.p||b.n-a.n);return a[0]}
window.adaptiveDue=id=>{const r=data().reviews[String(id)];return !!r&&r.due<=Date.now()};
window.adaptiveScore=q=>{const st=window.state(),a=st.answers[String(q.id)],r=data().reviews[String(q.id)],w=weakest();let score=0;if(r?.due<=Date.now())score+=100;if(a&&!a.correct)score+=70;if(w&&subj(q)===w.s)score+=45;if(!a)score+=15;if(r?.last)score+=Math.min(30,(Date.now()-r.last)/DAY);return score};
window.studyNow=async()=>{while(await window.loadMoreQuestionData?.()){}const ranked=(window.Q||[]).filter(q=>!window.questionAllowed||window.questionAllowed(q)).sort((a,b)=>window.adaptiveScore(b)-window.adaptiveScore(a)).slice(0,30);sessionIds=new Set(ranked.map(q=>String(q.id)));sessionOn=true;window.setFeedMode?.('smart');alert('Sessão inteligente criada com '+ranked.length+' questões: revisões vencidas, erros reincidentes, pontos fracos e questões novas.');};let sessionOn=false,sessionIds=new Set();window.smartSessionAllows=q=>!sessionOn||sessionIds.has(String(q.id));
function draw(){const host=document.getElementById('adaptivePanel');if(!host)return;const {by,topics}=metrics(),rows=Object.entries(by).map(([s,x])=>({s,p:pct(x),n:x.n})).sort((a,b)=>a.p-b.p),weakTopics=Object.entries(topics).map(([s,x])=>({s,p:pct(x),n:x.n})).filter(x=>x.n>=2).sort((a,b)=>a.p-b.p).slice(0,5),d=data(),due=Object.values(d.reviews).filter(r=>r.due<=Date.now()).length;
const pr=readiness();host.innerHTML='<h3>🧠 Estudo inteligente</h3><div style="text-align:center;padding:10px"><small>Índice de prontidão para prova</small><div style="font-size:38px;font-weight:900">'+pr.score+'/100</div><b>'+pr.label+'</b><br><small>Retenção '+pr.ret+'% • Cobertura '+pr.coverage+'%</small></div><p><b>'+due+'</b> revisões vencidas.</p><button class="action" onclick="studyNow()">O que estudar agora?</button><h4>Mapa de domínio</h4>'+(rows.length?rows.map(x=>'<p><b>'+window.esc(x.s)+'</b><br><small>'+x.p+'% • '+level(x.p,x.n)+' • '+x.n+' respondidas</small>'+bar(x.p)+'</p>').join(''):'<p><small>Responda questões para formar seu mapa.</small></p>')+(weakTopics.length?'<h4>Pontos fracos por assunto</h4>'+weakTopics.map(x=>'<p><small>'+window.esc(x.s)+' — '+x.p+'% em '+x.n+' questões</small>'+bar(x.p)+'</p>').join(''):'')}
window.openErrorNotebook=async()=>{while(await window.loadMoreQuestionData?.()){}const st=window.state(),groups={};for(const q of window.Q||[]){const a=st.answers[String(q.id)];if(!a||a.correct!==false)continue;const s=subj(q),t=topic(q),k=s+'|||'+t;(groups[k]??={s,t,items:[]}).items.push(q)}const list=Object.values(groups).sort((a,b)=>b.items.length-a.items.length),box=document.getElementById('errorNotebookBody');if(!box)return;box.innerHTML=list.length?'<p><b>'+list.reduce((n,g)=>n+g.items.length,0)+'</b> erros atuais em <b>'+list.length+'</b> assuntos.</p>'+list.map(g=>'<details class="card"><summary><b>'+window.esc(g.s)+'</b><br><small>'+window.esc(g.t)+' • '+g.items.length+' erro(s)</small></summary>'+g.items.slice(0,20).map(q=>'<p style="border-top:1px solid #24517c;padding-top:9px">'+window.esc(q.q||q.question||'')+'<br><small><b>Gabarito: '+(Boolean(q.a??q.answer)?'CERTO':'ERRADO')+'</b> — '+window.esc(q.c||q.comment||'Sem comentário.')+'</small></p>').join('')+'</details>').join(''):'<p>Nenhum erro registrado.</p>';document.getElementById('errorNotebook').classList.add('show')};
function inject(){const stats=document.getElementById('stats');if(!stats||document.getElementById('adaptivePanel'))return;const d=document.createElement('div');d.id='adaptivePanel';d.className='card';stats.appendChild(d);const more=document.getElementById('more');if(more&&!document.getElementById('errorNotebookCard')){const ec=document.createElement('div');ec.id='errorNotebookCard';ec.className='card';ec.innerHTML='<h3>📕 Caderno automático de erros</h3><p>Agrupa seus erros por matéria e assunto e mostra os pontos de maior reincidência.</p><button class="action" onclick="openErrorNotebook()">Abrir caderno de erros</button>';more.prepend(ec);const modal=document.createElement('div');modal.id='errorNotebook';modal.style.cssText='display:none;position:fixed;inset:0;z-index:9999;background:#020b17f5;padding:18px;overflow:auto';modal.innerHTML='<div style="max-width:560px;margin:auto"><h2>📕 Caderno de erros</h2><div id="errorNotebookBody"></div><button class="action" onclick="document.getElementById(\'errorNotebook\').classList.remove(\'show\')">Fechar</button></div>';document.body.appendChild(modal);const st=document.createElement('style');st.textContent='#errorNotebook.show{display:block!important} #errorNotebook summary{cursor:pointer}';document.head.appendChild(st)}draw()}
window.addEventListener('study-config-change',draw);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
window.drawAdaptive=draw;
})();