(function(){
const KEY='sefaz-hipotetico-cycle-timer-v3',APPKEY='sefaz-hipotetico-state-v1';let tick=null,notified=false;
function appState(){try{return Object.assign({answers:{}},JSON.parse(localStorage.getItem(APPKEY)||'{}'))}catch(e){return{answers:{}}}}
function state(){try{return Object.assign({total:14400,left:14400,running:false,end:0,start:null,cycleResolved:0,cycleWrong:0,history:[]},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return{total:14400,left:14400,running:false,end:0,start:null,cycleResolved:0,cycleWrong:0,history:[]}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function current(s){return s.running&&s.end?Math.max(0,Math.ceil((s.end-Date.now())/1000)):Math.max(0,s.left||0)}
function fmt(n){n=Math.max(0,n|0);let h=Math.floor(n/3600),m=Math.floor(n%3600/60),x=n%60;return[h,m,x].map(v=>String(v).padStart(2,'0')).join(':')}
function begin(s){if(!s.start){s.start=Date.now();s.cycleResolved=0;s.cycleWrong=0}}
function record(s,reason){if(!s.start)return null;let r={at:Date.now(),startedAt:s.start,duration:Math.max(0,Math.round((Date.now()-s.start)/1000)),resolved:s.cycleResolved||0,wrong:s.cycleWrong||0,reason};s.history=Array.isArray(s.history)?s.history:[];s.history.unshift(r);s.history=s.history.slice(0,100);s.start=null;save(s);drawHistory(s);return r}
function drawHistory(s=state()){let box=document.getElementById('cycleHistory');if(!box)return;let h=s.history||[];box.innerHTML='<b>📋 Histórico dos ciclos</b>'+(h.length?h.slice(0,20).map((r,i)=>'<div style="padding:8px 0;border-bottom:1px solid #24517c"><small>'+new Date(r.at).toLocaleString('pt-BR')+'</small><br><strong>'+r.resolved+' resolvidas</strong> • <strong>'+r.wrong+' erradas</strong> • '+fmt(r.duration)+'</div>').join(''):'<p>Nenhum ciclo concluído ainda.</p>')}
function updateCounters(s=state()){let a=document.getElementById('cycleResolved'),b=document.getElementById('cycleWrong');if(a)a.textContent=s.cycleResolved||0;if(b)b.textContent=s.cycleWrong||0}
window.addEventListener('cycle-answer',e=>{let s=state();if(!s.start)return;s.cycleResolved=(s.cycleResolved||0)+1;if(e.detail?.correct===false)s.cycleWrong=(s.cycleWrong||0)+1;save(s);updateCounters(s)});
function showDone(r){let m=document.getElementById('cycleTimerDone');if(!m)return;m.querySelector('p').innerHTML='<b>'+(r?.resolved||0)+' questões resolvidas • '+(r?.wrong||0)+' erradas</b>';m.classList.add('show')}
function hideDone(){document.getElementById('cycleTimerDone')?.classList.remove('show')}
function draw(){let s=state(),left=current(s);if(s.running&&left<=0){s.running=false;s.left=0;s.end=0;let r=record(s,'tempo');save(s);if(!notified){notified=true;showDone(r)}}let t=document.getElementById('cycleTimerTime'),bar=document.getElementById('cycleTimerBar'),btn=document.getElementById('cycleTimerToggle');if(t)t.textContent=fmt(left)+' restantes';if(bar)bar.style.width=(s.total?Math.min(100,Math.max(0,(s.total-left)/s.total*100)):0)+'%';if(btn)btn.textContent=s.running?'⏸ Pausar':'▶ Iniciar';updateCounters(s)}
function setMinutes(){let s=state(),v=prompt('Tempo total do ciclo em minutos:',String(Math.round(s.total/60)));if(v===null)return;let min=Number(v);if(!Number.isFinite(min)||min<1||min>1440){alert('Informe um valor entre 1 e 1440 minutos.');return}s.total=Math.round(min*60);s.left=s.total;s.running=false;s.end=0;s.start=null;s.cycleResolved=0;s.cycleWrong=0;save(s);draw()}
function toggle(){let s=state(),left=current(s);if(s.running){s.left=left;s.running=false;s.end=0}else{if(left<=0)left=s.total;s.left=left;begin(s);s.running=true;s.end=Date.now()+left*1000;notified=false;hideDone()}save(s);draw()}
function reset(){if(!confirm('Reiniciar o ciclo? O resultado atual será registrado.'))return;let s=state();record(s,'reiniciado');s.left=s.total;s.running=false;s.end=0;s.start=null;s.cycleResolved=0;s.cycleWrong=0;save(s);draw()}
function finish(){let s=state(),r=s.start?record(s,'encerrado'):null;s.running=false;s.end=0;s.left=s.total;s.cycleResolved=0;s.cycleWrong=0;save(s);hideDone();draw();return r}
function newCycle(){let s=state();if(s.start)record(s,'novo ciclo');s.left=s.total;s.start=null;s.cycleResolved=0;s.cycleWrong=0;begin(s);s.running=true;s.end=Date.now()+s.total*1000;notified=false;hideDone();save(s);draw()}
function init(){if(document.getElementById('cycleTimer'))return true;let app=document.querySelector('.app');if(!app)return false;let style=document.createElement('style');style.textContent='#cycleTimer{position:sticky;top:0;z-index:50;background:#061f39;border-bottom:1px solid #24517c;padding:5px 8px;display:grid;grid-template-columns:1fr auto;gap:3px 6px;align-items:center}#cycleTimerTime{font-weight:700;font-size:15px}#cycleLive{grid-column:1/-1;display:flex;gap:14px;font-size:12px;color:#dcecff}#cycleLive b{color:#ffd52e}#cycleTimerBtns{display:flex;gap:4px}#cycleTimer button{padding:5px 8px;font-size:12px;font-weight:700;border-radius:8px;background:#ffd52e;color:#07182e;border:0;min-height:32px}#cycleTimerTrack{grid-column:1/-1;height:3px;background:#183b5e;border-radius:9px;overflow:hidden}#cycleTimerBar{height:100%;background:#43e09d}#cycleTimerDone{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,8,18,.88);align-items:center;justify-content:center;padding:22px}#cycleTimerDone.show{display:flex}#cycleTimerDoneBox{width:min(440px,100%);background:#08233e;border:2px solid #43e09d;border-radius:20px;padding:28px 20px;text-align:center}';document.head.appendChild(style);let d=document.createElement('div');d.id='cycleTimer';d.innerHTML='<div><small>⏱ Ciclo de estudo</small><div id="cycleTimerTime">04:00:00 restantes</div></div><div id="cycleTimerBtns"><button id="cycleTimerSet">⚙ Tempo</button><button id="cycleTimerToggle">▶ Iniciar</button><button id="cycleTimerReset">↺</button></div><div id="cycleLive"><span>Resolvidas: <b id="cycleResolved">0</b></span><span>Erradas: <b id="cycleWrong">0</b></span></div><div id="cycleTimerTrack"><div id="cycleTimerBar"></div></div>';app.insertBefore(d,app.firstChild);let modal=document.createElement('div');modal.id='cycleTimerDone';modal.innerHTML='<div id="cycleTimerDoneBox"><div style="font-size:54px">⏰</div><h2>CICLO ENCERRADO</h2><p></p><button id="cycleTimerFinish">✓ Encerrar</button> <button id="cycleTimerNew">▶ Novo ciclo</button></div>';document.body.appendChild(modal);let more=document.getElementById('more');if(more&&!document.getElementById('cycleHistory')){let h=document.createElement('div');h.id='cycleHistory';h.className='card';more.appendChild(h)}document.getElementById('cycleTimerSet').onclick=setMinutes;document.getElementById('cycleTimerToggle').onclick=toggle;document.getElementById('cycleTimerReset').onclick=reset;document.getElementById('cycleTimerFinish').onclick=finish;document.getElementById('cycleTimerNew').onclick=newCycle;drawHistory();draw();tick=setInterval(draw,1000);return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();