(function(){
const KEY='sefaz-hipotetico-cycle-timer-v2',APPKEY='sefaz-hipotetico-state-v1';let tick=null,notified=false;
function appState(){try{return Object.assign({answers:{}},JSON.parse(localStorage.getItem(APPKEY)||'{}'))}catch(e){return{answers:{}}}}
function snapshot(){const a=appState().answers||{},ids=Object.keys(a);return{resolved:ids.length,wrong:ids.filter(id=>a[id]&&a[id].correct===false).length}}
function state(){try{return Object.assign({total:14400,left:14400,running:false,end:0,start:null,history:[]},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return{total:14400,left:14400,running:false,end:0,start:null,history:[]}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function current(s){if(s.running&&s.end)return Math.max(0,Math.ceil((s.end-Date.now())/1000));return Math.max(0,s.left||0)}
function fmt(n){n=Math.max(0,n|0);let h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function begin(s){if(!s.start){const x=snapshot();s.start={at:Date.now(),resolved:x.resolved,wrong:x.wrong}}}
function record(s,reason){if(!s.start)return null;const x=snapshot(),r={at:Date.now(),startedAt:s.start.at,duration:Math.max(0,Math.round((Date.now()-s.start.at)/1000)),resolved:Math.max(0,x.resolved-s.start.resolved),wrong:Math.max(0,x.wrong-s.start.wrong),reason};s.history=Array.isArray(s.history)?s.history:[];s.history.unshift(r);s.history=s.history.slice(0,100);s.start=null;save(s);drawHistory(s);return r}
function drawHistory(s=state()){const box=document.getElementById('cycleHistory');if(!box)return;const h=s.history||[];box.innerHTML=h.length?'<b>📋 Histórico dos ciclos</b>'+h.slice(0,20).map((r,i)=>'<div style="padding:8px 0;border-bottom:1px solid #24517c"><small>Ciclo '+(h.length-i)+' • '+new Date(r.at).toLocaleString('pt-BR')+'</small><br><strong>'+r.resolved+' resolvidas</strong> • <strong>'+r.wrong+' erradas</strong> • '+fmt(r.duration)+'</div>').join(''):'<b>📋 Histórico dos ciclos</b><p>Nenhum ciclo concluído ainda.</p>'}
function showDone(r){let m=document.getElementById('cycleTimerDone');if(m){let p=m.querySelector('p');if(p)p.innerHTML='Você concluiu o tempo programado.<br><b>'+(r?.resolved||0)+' questões resolvidas • '+(r?.wrong||0)+' erradas</b>';m.classList.add('show')}}
function hideDone(){let m=document.getElementById('cycleTimerDone');if(m)m.classList.remove('show')}
function draw(){let s=state(),left=current(s);if(s.running&&left<=0){s.running=false;s.left=0;s.end=0;const r=record(s,'tempo');save(s);if(!notified){notified=true;showDone(r)}}let t=document.getElementById('cycleTimerTime'),bar=document.getElementById('cycleTimerBar'),btn=document.getElementById('cycleTimerToggle');if(t)t.textContent=fmt(left)+' restantes';if(bar)bar.style.width=(s.total?Math.min(100,Math.max(0,(s.total-left)/s.total*100)):0)+'%';if(btn)btn.textContent=s.running?'⏸ Pausar':'▶ Iniciar'}
function setMinutes(){let s=state(),v=prompt('Tempo total do ciclo em minutos:',String(Math.round(s.total/60)));if(v===null)return;let min=Number(v);if(!Number.isFinite(min)||min<1||min>1440){alert('Informe um valor entre 1 e 1440 minutos.');return}s.total=Math.round(min*60);s.left=s.total;s.running=false;s.end=0;s.start=null;notified=false;hideDone();save(s);draw()}
function toggle(){let s=state(),left=current(s);if(s.running){s.left=left;s.running=false;s.end=0}else{if(left<=0)left=s.total;s.left=left;begin(s);s.running=true;s.end=Date.now()+left*1000;notified=false;hideDone()}save(s);draw()}
function reset(){if(!confirm('Reiniciar o marcador do ciclo? O ciclo atual será registrado.'))return;let s=state();record(s,'reiniciado');s.left=s.total;s.running=false;s.end=0;s.start=null;notified=false;hideDone();save(s);draw()}
function finish(){let s=state();if(s.start)record(s,'encerrado');s.running=false;s.end=0;s.left=s.total;save(s);hideDone();draw()}
function newCycle(){let s=state();if(s.start)record(s,'novo ciclo');s.left=s.total;begin(s);s.running=true;s.end=Date.now()+s.total*1000;notified=false;hideDone();save(s);draw()}
function init(){if(document.getElementById('cycleTimer'))return true;let app=document.querySelector('.app');if(!app)return false;let style=document.createElement('style');style.textContent='#cycleTimer,#cycleTimer *{font-family:system-ui!important}#cycleTimer{position:sticky;top:0;z-index:50;background:#061f39;border-bottom:1px solid #24517c;padding:4px 8px;display:grid;grid-template-columns:1fr auto;gap:3px 6px;align-items:center;font-size:13px}#cycleTimer small{font-size:13px;color:#fff}#cycleTimerTime{font-weight:700;font-variant-numeric:tabular-nums;font-size:15px;color:#fff}#cycleTimerBtns{display:flex;gap:4px}#cycleTimer button{padding:5px 8px;font-size:12px;font-weight:700;border-radius:8px;background:#ffd52e!important;color:#07182e!important;border:0!important;min-height:32px}#cycleTimerTrack{grid-column:1/-1;height:3px;background:#183b5e;border-radius:9px;overflow:hidden}#cycleTimerBar{height:100%;width:0;background:#43e09d;transition:width .3s}#cycleTimerDone{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,8,18,.88);align-items:center;justify-content:center;padding:22px}#cycleTimerDone.show{display:flex}#cycleTimerDoneBox{width:min(440px,100%);background:#08233e;border:2px solid #43e09d;border-radius:20px;padding:28px 20px;text-align:center}#cycleTimerDoneIcon{font-size:54px}#cycleTimerDoneActions{display:grid;gap:10px}#cycleTimerDoneActions button{padding:14px;font-size:15px}@media(min-width:700px){.app{max-width:calc(100vw - 32px)!important;width:calc(100vw - 32px)!important}.top,.feedfilter,nav{width:calc(100vw - 32px)!important;max-width:none!important}.q{padding-left:42px!important;padding-right:42px!important}}';document.head.appendChild(style);let d=document.createElement('div');d.id='cycleTimer';d.innerHTML='<div><small>⏱ Ciclo de estudo</small><div id="cycleTimerTime">04:00:00 restantes</div></div><div id="cycleTimerBtns"><button id="cycleTimerSet">⚙ Tempo</button><button id="cycleTimerToggle">▶ Iniciar</button><button id="cycleTimerReset">↺</button></div><div id="cycleTimerTrack"><div id="cycleTimerBar"></div></div>';app.insertBefore(d,app.firstChild);let modal=document.createElement('div');modal.id='cycleTimerDone';modal.innerHTML='<div id="cycleTimerDoneBox"><div id="cycleTimerDoneIcon">⏰</div><h2>TEMPO DO CICLO ENCERRADO</h2><p></p><div id="cycleTimerDoneActions"><button id="cycleTimerFinish">✓ Encerrar ciclo</button><button id="cycleTimerNew">▶ Novo ciclo</button></div></div>';document.body.appendChild(modal);let more=document.getElementById('more');if(more){let h=document.createElement('div');h.id='cycleHistory';h.className='card';more.appendChild(h)}document.getElementById('cycleTimerSet').onclick=setMinutes;document.getElementById('cycleTimerToggle').onclick=toggle;document.getElementById('cycleTimerReset').onclick=reset;document.getElementById('cycleTimerFinish').onclick=finish;document.getElementById('cycleTimerNew').onclick=newCycle;drawHistory();draw();tick=setInterval(draw,1000);return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();