(function(){
const KEY='sefaz-hipotetico-notes-v1';let editId=null,questionCtx=null;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function all(){try{let a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return []}}
function save(a){localStorage.setItem(KEY,JSON.stringify(a))}function now(){return new Date().toISOString()}function catalog(){return window.SEFAZ_STUDY||[]}
function fillSubjects(){let s=document.getElementById('noteSubject');if(!s)return;let cur=s.value;s.innerHTML='<option value="">Sem matéria</option>'+catalog().map(x=>'<option>'+esc(x.subject)+'</option>').join('');s.value=cur;fillLessons()}
function fillLessons(){let su=document.getElementById('noteSubject'),le=document.getElementById('noteLesson');if(!su||!le)return;let cur=le.value,g=catalog().find(x=>x.subject===su.value);le.innerHTML='<option value="">Sem aula</option>'+((g&&g.lessons)||[]).map(x=>'<option>'+esc(x)+'</option>').join('');le.value=cur}
function form(n){n=n||{};editId=n.id||null;document.getElementById('noteTitle').value=n.title||'';document.getElementById('noteText').value=n.text||'';document.getElementById('noteSubject').value=n.subject||'';fillLessons();document.getElementById('noteLesson').value=n.lesson||'';questionCtx=n.question||null;document.getElementById('noteQuestionRef').textContent=questionCtx?('Questão vinculada: '+(questionCtx.id||'')+' • '+(questionCtx.subject||'')):'Sem questão vinculada';document.getElementById('noteCancel').classList.toggle('hidden',!editId)}
window.saveNote=function(){let text=document.getElementById('noteText').value.trim();if(!text){alert('Escreva a anotação.');return}let a=all(),old=editId&&a.find(x=>x.id===editId),n={id:editId||('n'+Date.now()),title:document.getElementById('noteTitle').value.trim(),text,subject:document.getElementById('noteSubject').value,lesson:document.getElementById('noteLesson').value,question:questionCtx,created:old?old.created:now(),updated:now()};if(old)Object.assign(old,n);else a.unshift(n);save(a);form();render()};
window.cancelNote=function(){form()};window.editNote=function(id){let n=all().find(x=>x.id===id);if(n){form(n);document.getElementById('noteText').focus();window.scrollTo(0,0)}};window.deleteNote=function(id){if(!confirm('Excluir esta anotação?'))return;save(all().filter(x=>x.id!==id));if(editId===id)form();render()};
function render(){let box=document.getElementById('notesList');if(!box)return;let q=(document.getElementById('noteSearch').value||'').toLowerCase(),a=all().filter(n=>[n.title,n.text,n.subject,n.lesson,n.question&&n.question.id].join(' ').toLowerCase().includes(q));document.getElementById('notesCount').textContent=a.length+' anotação(ões)';box.innerHTML=a.length?a.map(n=>'<div class="card"><b>'+esc(n.title||'Anotação')+'</b><div><small>'+esc(n.subject||'Geral')+(n.lesson?' • '+esc(n.lesson):'')+' • '+new Date(n.updated).toLocaleString('pt-BR')+'</small></div><p style="white-space:pre-wrap">'+esc(n.text)+'</p>'+(n.question?'<small>🔗 Questão '+esc(n.question.id||'')+'</small>':'')+'<div class="noteActions"><button onclick="editNote(\''+n.id+'\')">Editar</button><button onclick="deleteNote(\''+n.id+'\')">Excluir</button></div></div>').join(''):'<div class="card">Nenhuma anotação encontrada.</div>'}window.searchNotes=render;
window.exportNotes=function(){let blob=new Blob([JSON.stringify({version:1,exported_at:now(),notes:all()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='sefaz-hipotetico-anotacoes-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
window.printNotes=function(){let a=all(),w=window.open('','_blank');if(!w)return;w.document.write('<!doctype html><meta charset="utf-8"><title>Anotações</title><style>body{font:14px Arial;max-width:850px;margin:30px auto}article{border-bottom:1px solid #bbb;padding:14px 0;break-inside:avoid}</style><h1>Anotações de estudo — SEFAZ-Hipotético</h1>'+a.map(n=>'<article><h2>'+esc(n.title||'Anotação')+'</h2><small>'+esc(n.subject||'Geral')+(n.lesson?' • '+esc(n.lesson):'')+'</small><p>'+esc(n.text)+'</p></article>').join(''));w.document.close();setTimeout(()=>w.print(),250)};
function tabNotes(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));document.getElementById('feedFilter')?.classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('on'));document.getElementById('notes').classList.remove('hidden');fillSubjects();render();window.scrollTo(0,0)}window.tabNotes=tabNotes;
window.noteCurrentQuestion=function(q){questionCtx={id:q.id||'',subject:q.s||q.source_package_canonical||q.source_package||'',lesson:(window.sefazQuestionLesson&&window.sefazQuestionLesson(q))||q.t||''};tabNotes();fillSubjects();document.getElementById('noteSubject').value=questionCtx.subject;fillLessons();document.getElementById('noteQuestionRef').textContent='Questão vinculada: '+questionCtx.id+' • '+questionCtx.subject};
function injectQuestionButtons(){document.querySelectorAll('#feed .q').forEach(el=>{if(el.querySelector('.noteQuestion'))return;let id=el.dataset&&el.dataset.id,q=(window.Q||window.questions||[]).find&&((window.Q||window.questions).find(x=>String(x.id)===String(id)));if(!q)return;let b=document.createElement('button');b.className='star noteQuestion';b.textContent='📝 Anotar esta questão';b.onclick=()=>noteCurrentQuestion(q);el.appendChild(b)})}
function init(){let app=document.querySelector('.app'),nav=app&&app.querySelector('nav'),more=document.getElementById('more');if(!app||!nav||!more)return false;if(document.getElementById('notes'))return true;let style=document.createElement('style');style.textContent='.noteActions{display:flex;gap:8px}.noteActions button{padding:8px 12px;border-radius:10px;border:1px solid #24517c;background:#07182e;color:#fff}.noteTools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.moreNotesBtn{width:100%;padding:14px;margin:8px 0;border-radius:12px;border:1px solid #24517c;background:#0b2848;color:#fff;font-size:16px;text-align:left}';document.head.appendChild(style);let s=document.createElement('section');s.id='notes';s.className='panel hidden';s.innerHTML='<h2>📝 Anotações</h2><p>Pensamentos e registros livres de estudo. Salvos neste aparelho.</p><input id="noteTitle" placeholder="Título (opcional)"><select id="noteSubject"></select><select id="noteLesson"></select><div id="noteQuestionRef" class="card">Sem questão vinculada</div><textarea id="noteText" rows="8" placeholder="Escreva sua anotação..."></textarea><button class="primary" onclick="saveNote()">Salvar anotação</button><button id="noteCancel" class="primary hidden" onclick="cancelNote()">Cancelar edição</button><hr><input id="noteSearch" placeholder="Pesquisar anotações" oninput="searchNotes()"><div class="noteTools"><button onclick="printNotes()">🖨️ Imprimir</button><button onclick="exportNotes()">⬇️ Backup</button></div><p id="notesCount"></p><div id="notesList"></div>';app.insertBefore(s,nav);document.getElementById('noteSubject').onchange=fillLessons;let old=document.getElementById('nnotes');if(old)old.remove();let b=document.createElement('button');b.id='moreNotes';b.className='moreNotesBtn';b.innerHTML='📝 Anotações';b.onclick=tabNotes;more.insertBefore(b,more.firstChild);window.fillLessons=fillLessons;fillSubjects();setInterval(injectQuestionButtons,800);return true}let t=setInterval(()=>{if(init())clearInterval(t)},50);
})();