// Feed virtualizado: mantém no máximo 9 Shorts no DOM, mesmo com banco de 50 mil.
(()=>{
const WINDOW=9,STEP=4;let start=0,mode='pending',qById=new Map(),indexedLength=0,busy=false;
function indexNew(){const a=window.Q||[];if(a.length<indexedLength){qById.clear();indexedLength=0}for(let i=indexedLength;i<a.length;i++)qById.set(String(a[i].id),a[i]);indexedLength=a.length}
function safeId(s){return String(s||'').replace(/['"]/g,'')}
function feedbackHtml(q,correct){return '<b>'+(correct?'✅ Acertou':'❌ Errou')+'</b><p><strong>Resposta correta: '+(Boolean(q.a??q.answer)?'CERTO':'ERRADO')+'.</strong></p><p>'+window.esc(q.c||q.comment||'Comentário ainda não disponível.')+'</p>'}
function item(q,s){const id=safeId(q.id),saved=s.answers[id],ans=Boolean(q.a??q.answer);let c1='opt',c2='opt',disabled='';if(saved){disabled=' disabled';const chosen=Boolean(saved.v);(ans?c1:c2)+=' ok';if(chosen!==ans)(chosen?c1:c2)+=' no'}return '<article class="q" data-id="'+id+'"><div class="tag">'+window.esc(q.s||q.subject||'SEFAZ-Hipotético')+'</div><div class="topic">'+window.esc(q.t||q.topic||'')+'</div><h1>'+window.esc(q.q||q.question||'')+'</h1><button class="'+c1+'" data-value="true" onclick="answer(\''+id+'\',true,this)"'+disabled+'>CERTO</button><button class="'+c2+'" data-value="false" onclick="answer(\''+id+'\',false,this)"'+disabled+'>ERRADO</button><div class="feedback '+(saved?'':'hidden')+'">'+(saved?feedbackHtml(q,saved.correct):'')+'</div><button class="star" onclick="favorite(\''+id+'\',this)">'+(s.fav[id]?'★':'☆')+' Favoritar</button></article>'}
function eligible(s){const a=window.Q||[],out=[];for(let i=0;i<a.length;i++){const done=!!s.answers[a[i].id];if(mode==='all'||(mode==='resolved'?done:!done))out.push(a[i])}return out}
window.render=function(reset=false){if(busy)return;busy=true;requestAnimationFrame(()=>{indexNew();const box=document.getElementById('feed');if(!box){busy=false;return}const s=window.state(),all=eligible(s);if(reset)start=0;if(start>=all.length)start=Math.max(0,all.length-WINDOW);const list=all.slice(start,start+WINDOW);box.innerHTML=list.length?list.map(q=>item(q,s)).join(''):'<section class="q"><div class="card"><h2>Nenhuma questão nesta lista</h2><p>Continue avançando para carregar mais questões.</p></div></section>';box.scrollTop=0;busy=false})};
window.answer=function(id,v,b){indexNew();const q=qById.get(String(id));if(!q)return;const ans=Boolean(q.a??q.answer),correct=ans===v,s=window.state();s.answers[id]={v,correct};window.save(s);const art=b.closest('.q');if(!art)return;art.querySelectorAll('.opt').forEach(x=>{x.disabled=true;x.classList.remove('ok','no');const val=x.dataset.value==='true';if(val===ans)x.classList.add('ok');if(val===v&&val!==ans)x.classList.add('no')});const fb=art.querySelector('.feedback');if(fb){fb.classList.remove('hidden');fb.innerHTML=feedbackHtml(q,correct)}window.stats?.()};
window.favorite=function(id,b){const s=window.state();s.fav[id]=!s.fav[id];if(!s.fav[id])delete s.fav[id];window.save(s);if(b)b.innerHTML=(s.fav[id]?'★':'☆')+' Favoritar';window.stats?.()};
window.setFeedMode=function(m){mode=m;start=0;['fp','fr','fa'].forEach(x=>document.getElementById(x)?.classList.remove('on'));document.getElementById(m==='pending'?'fp':m==='resolved'?'fr':'fa')?.classList.add('on');window.render(true)};
const feed=document.getElementById('feed');if(feed){let last=0;feed.addEventListener('scroll',()=>{if(busy)return;const now=performance.now();if(now-last<180)return;last=now;if(feed.scrollTop+feed.clientHeight>=feed.scrollHeight-feed.clientHeight*.7){const s=window.state(),all=eligible(s);if(start+WINDOW<all.length){start+=STEP;window.render(false)}else window.loadMoreQuestionData?.()}},{passive:true})}
})();