// Shorts leve e estável: um card por vez, sem rerender durante a rolagem.
(()=>{
let pos=0,mode='pending',qById=new Map(),indexedLength=0,rendering=false;
function indexNew(){const a=window.Q||[];if(a.length<indexedLength){qById.clear();indexedLength=0}for(let i=indexedLength;i<a.length;i++)qById.set(String(a[i].id),a[i]);indexedLength=a.length}
function safeId(s){return String(s||'').replace(/['"]/g,'')}
function eligible(){const s=window.state(),a=window.Q||[],out=[];for(let i=0;i<a.length;i++){const done=!!s.answers[a[i].id];if(mode==='all'||(mode==='resolved'?done:!done))out.push(a[i])}return out}
function feedbackHtml(q,correct){if(correct)return '<b>✅ Acertou</b>';return '<b>❌ Errou</b><p><strong>Resposta correta: '+(Boolean(q.a??q.answer)?'CERTO':'ERRADO')+'.</strong></p><p>'+window.esc(q.c||q.comment||'Comentário ainda não disponível.')+'</p>'}
function item(q,s){const id=safeId(q.id),saved=s.answers[id],ans=Boolean(q.a??q.answer);let c1='opt',c2='opt',disabled='';if(saved){disabled=' disabled';const chosen=Boolean(saved.v);if(ans)c1+=' ok';else c2+=' ok';if(chosen!==ans){if(chosen)c1+=' no';else c2+=' no'}}return '<article class="q" data-id="'+id+'"><div class="tag">'+window.esc(q.s||q.subject||'Roleta dos Preguiçosos')+'</div><div class="topic">'+window.esc(q.t||q.topic||'')+'</div><h1>'+window.esc(q.q||q.question||'')+'</h1><button class="'+c1+'" data-value="true" onclick="answer(\''+id+'\',true,this)"'+disabled+'>CERTO</button><button class="'+c2+'" data-value="false" onclick="answer(\''+id+'\',false,this)"'+disabled+'>ERRADO</button><div class="feedback '+(saved?'':'hidden')+'">'+(saved?feedbackHtml(q,saved.correct):'')+'</div><button class="star" onclick="favorite(\''+id+'\',this)">'+(s.fav[id]?'★':'☆')+' Favoritar</button><div style="display:flex;gap:8px;margin-top:14px"><button class="opt" style="text-align:center;flex:1" onclick="prevShort()">◀ Anterior</button><button class="opt" style="text-align:center;flex:1" onclick="nextShort()">Próxima ▶</button></div></article>'}
window.render=function(reset=false){if(rendering)return;rendering=true;requestAnimationFrame(()=>{indexNew();const box=document.getElementById('feed');if(!box){rendering=false;return}if(reset)pos=0;const list=eligible();if(pos>=list.length)pos=Math.max(0,list.length-1);const q=list[pos],s=window.state();box.innerHTML=q?item(q,s):'<section class="q"><div class="card"><h2>Carregando questões…</h2><p>Aguarde um instante.</p></div></section>';box.scrollTop=0;rendering=false})};
window.nextShort=async function(){let list=eligible();if(pos+1<list.length){pos++;window.render(false);return}const loaded=await window.loadMoreQuestionData?.();list=eligible();if(loaded&&pos+1<list.length)pos++;window.render(false)};
window.prevShort=function(){if(pos>0)pos--;window.render(false)};
window.answer=function(id,v,b){indexNew();const q=qById.get(String(id));if(!q)return;const ans=Boolean(q.a??q.answer),correct=ans===v,s=window.state();s.answers[id]={v,correct};window.save(s);const art=b.closest('.q');if(!art)return;art.querySelectorAll('button.opt[data-value]').forEach(x=>{x.disabled=true;x.classList.remove('ok','no');const val=x.dataset.value==='true';if(val===ans)x.classList.add('ok');if(val===v&&val!==ans)x.classList.add('no')});const fb=art.querySelector('.feedback');if(fb){fb.classList.remove('hidden');fb.innerHTML=feedbackHtml(q,correct)}window.stats?.()};
window.favorite=function(id,b){const s=window.state();s.fav[id]=!s.fav[id];if(!s.fav[id])delete s.fav[id];window.save(s);if(b)b.innerHTML=(s.fav[id]?'★':'☆')+' Favoritar';window.stats?.()};
window.setFeedMode=function(m){mode=m;pos=0;['fp','fr','fa'].forEach(x=>document.getElementById(x)?.classList.remove('on'));document.getElementById(m==='pending'?'fp':m==='resolved'?'fr':'fa')?.classList.add('on');window.render(true)};
const feed=document.getElementById('feed');if(feed){let y0=null;feed.addEventListener('touchstart',e=>{y0=e.touches?.[0]?.clientY??null},{passive:true});feed.addEventListener('touchend',e=>{if(y0===null)return;const y=e.changedTouches?.[0]?.clientY??y0,d=y-y0;y0=null;if(Math.abs(d)<55)return;if(d<0)window.nextShort();else window.prevShort()},{passive:true})}
})();