// Otimização para banco fragmentado: DOM curto, índice incremental e resposta visual correta.
(()=>{
const PAGE=16;let shown=PAGE,mode='pending',qById=new Map(),subjectCounts=new Map(),indexedLength=0,observer=null;
function indexNew(){const a=window.Q||[];if(a.length<indexedLength){qById.clear();subjectCounts.clear();indexedLength=0}for(let i=indexedLength;i<a.length;i++){const q=a[i];qById.set(String(q.id),q);const s=q.s||q.subject||'SEFAZ-Hipotético';subjectCounts.set(s,(subjectCounts.get(s)||0)+1)}indexedLength=a.length}
function safeId(s){return String(s||'').replace(/['"]/g,'')}
function item(q,s){const id=safeId(q.id),saved=s.answers[id],ans=Boolean(q.a??q.answer);let c1='opt',c2='opt',disabled='';if(saved){disabled=' disabled';const chosen=Boolean(saved.v);if(ans)c1+=' ok';else c2+=' ok';if(chosen!==ans)(chosen?c1:c2)+=' no'}return '<article class="q" data-id="'+id+'"><div class="tag">'+window.esc(q.s||q.subject||'SEFAZ-Hipotético')+'</div><div class="topic">'+window.esc(q.t||q.topic||'')+'</div><h1>'+window.esc(q.q||q.question||'')+'</h1><button class="'+c1+'" data-value="true" onclick="answer(\''+id+'\',true,this)"'+disabled+'>CERTO</button><button class="'+c2+'" data-value="false" onclick="answer(\''+id+'\',false,this)"'+disabled+'>ERRADO</button><div class="feedback '+(saved?'':'hidden')+'">'+(saved?feedbackHtml(q,saved.correct):'')+'</div><button class="star" onclick="favorite(\''+id+'\')">'+(s.fav[id]?'★':'☆')+' Favoritar</button></article>'}
function feedbackHtml(q,correct){return '<b>'+(correct?'✅ Acertou':'❌ Errou')+'</b><p><strong>Resposta correta: '+(Boolean(q.a??q.answer)?'CERTO':'ERRADO')+'.</strong></p><p>'+window.esc(q.c||q.comment||'Comentário ainda não disponível.')+'</p>'}
function eligible(q,s){const done=!!s.answers[q.id];return mode==='all'||(mode==='resolved'?done:!done)}
function collect(limit){const s=window.state(),out=[],a=window.Q||[];for(let i=0;i<a.length&&out.length<limit;i++)if(eligible(a[i],s))out.push(a[i]);return{s,out}}
window.render=function(reset=false){indexNew();if(reset)shown=PAGE;const box=document.getElementById('feed');if(!box)return;const{s,out}=collect(shown+1),more=out.length>shown,list=more?out.slice(0,shown):out;box.innerHTML=list.length?list.map(q=>item(q,s)).join('')+(more?'<div id="moreFeed" style="height:2px"></div>'):'<section class="q"><div class="card"><h2>Nenhuma questão nesta lista</h2><p>Altere o filtro ou continue carregando o banco.</p></div></section>';if(observer)observer.disconnect();if(more&&'IntersectionObserver'in window){observer=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){shown+=PAGE;window.render(false)}},{root:box,rootMargin:'400px'});observer.observe(document.getElementById('moreFeed'))}};
window.answer=function(id,v,b){indexNew();const q=qById.get(String(id));if(!q)return;const ans=Boolean(q.a??q.answer),correct=ans===v,s=window.state();s.answers[id]={v,correct};window.save(s);const art=b.closest('.q');if(!art)return;const buttons=[...art.querySelectorAll('.opt')];buttons.forEach(x=>{x.disabled=true;x.classList.remove('ok','no');const val=x.dataset.value==='true';if(val===ans)x.classList.add('ok');if(val===v&&val!==ans)x.classList.add('no')});const fb=art.querySelector('.feedback');if(fb){fb.classList.remove('hidden');fb.innerHTML=feedbackHtml(q,correct)}window.stats()};
window.favorite=function(id){const s=window.state();s.fav[id]=!s.fav[id];if(!s.fav[id])delete s.fav[id];window.save(s);window.render(false);window.stats()};
window.setFeedMode=function(m){mode=m;shown=PAGE;['fp','fr','fa'].forEach(x=>document.getElementById(x)?.classList.remove('on'));document.getElementById(m==='pending'?'fp':m==='resolved'?'fr':'fa')?.classList.add('on');window.render(true)};
window.subjects=function(){indexNew();const box=document.getElementById('sl');if(!box)return;const f=(document.getElementById('find')?.value||'').toLowerCase(),a=[...subjectCounts.entries()].filter(([x])=>x.toLowerCase().includes(f)).sort((a,b)=>a[0].localeCompare(b[0]));box.innerHTML=a.length?a.map(([x,n])=>'<div class="card"><b>'+window.esc(x)+'</b><br><small>'+n+' carregadas nesta sessão</small></div>').join(''):'<div class="card">Nenhuma matéria encontrada.</div>'};
})();