(function(){
let MANIFEST=null,CACHE={};const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const natural=(a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true});
async function manifest(){if(MANIFEST)return MANIFEST;let r=await fetch('reading-manifest.json',{cache:'no-store'});if(!r.ok)throw Error('manifest');MANIFEST=await r.json();return MANIFEST}
async function loadSubject(m){if(CACHE[m.subject])return CACHE[m.subject];let msg=document.getElementById('readingStatus');if(msg)msg.textContent='Carregando '+m.subject+'...';let r=await fetch(m.file);if(!r.ok)throw Error(m.file);let a=await r.json();CACHE[m.subject]=a;if(msg)msg.textContent='19 disciplinas • conteúdo carregado sob demanda';return a}
function show(x){let v=document.getElementById('readingBody');v.innerHTML='<div class="card"><small>'+esc(x.subject)+' • '+esc(x.lesson)+'</small><h2>'+esc(x.lesson)+'</h2><div class="readingSourceText">'+esc(x.text)+'</div></div>';localStorage.setItem('sefaz-hipotetico-reading-last-v2',JSON.stringify({subject:x.subject,lesson:x.lesson}));v.scrollIntoView({block:'start'})}
async function openSubject(m,d){try{let a=(await loadSubject(m)).sort((x,y)=>natural(x.lesson,y.lesson)),box=d.querySelector('.readingLessons');box.innerHTML='';a.forEach(x=>{let b=document.createElement('button');b.className='readingLesson';b.textContent=x.lesson;b.onclick=()=>show(x);box.appendChild(b)})}catch(e){d.querySelector('.readingLessons').innerHTML='<div class="card">Conteúdo desta disciplina ainda não foi publicado.</div>'}}
async function render(){let box=document.getElementById('readingSubjects'),msg=document.getElementById('readingStatus');try{let ms=await manifest();msg.textContent=ms.length+' disciplinas • '+ms.reduce((n,x)=>n+x.lessons,0)+' blocos de aula indexados';box.innerHTML='';ms.forEach(m=>{let d=document.createElement('details');d.className='card readingSubject';d.innerHTML='<summary><b>'+esc(m.subject)+'</b> <small>('+m.lessons+' blocos)</small></summary><div class="readingLessons"><small>Abra para carregar a disciplina.</small></div>';d.addEventListener('toggle',()=>{if(d.open&&!d.dataset.loaded){d.dataset.loaded='1';openSubject(m,d)}});box.appendChild(d)})}catch(e){msg.textContent='Índice de leitura indisponível.'}}
async function restore(){await render();try{let p=JSON.parse(localStorage.getItem('sefaz-hipotetico-reading-last-v2')||'null');if(!p)return;let ms=await manifest(),m=ms.find(x=>x.subject===p.subject);if(!m)return;let a=await loadSubject(m),x=a.find(z=>z.lesson===p.lesson);if(x)show(x)}catch(e){}}
function mode(on){document.body.classList.toggle('readingMode',!!on);document.getElementById('feedFilter')?.classList.toggle('hidden',!!on)}
function init(){if(document.getElementById('reading'))return true;let app=document.querySelector('.app'),nav=app&&app.querySelector('nav');if(!app||!nav)return false;let st=document.createElement('style');st.textContent='.readingSubject summary{cursor:pointer;padding:4px 0;font-size:17px}.readingLessons{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:10px}.readingLesson{padding:10px 7px;border:1px solid #24517c;border-radius:10px;background:#07182e;color:#fff;font-size:16px}.readingSourceText{white-space:pre-wrap;line-height:1.62;color:#e7eef7;font-size:18px}@media(min-width:700px){.readingLessons{grid-template-columns:repeat(4,minmax(0,1fr))}.readingSourceText{font-size:19px}}';document.head.appendChild(st);let s=document.createElement('section');s.id='reading';s.className='panel hidden';s.innerHTML='<h2>📖 Leitura</h2><p>Compilação Auditada V2. Cada disciplina é carregada somente quando aberta, economizando memória e dados no celular.</p><div id="readingStatus" class="card">Carregando índice...</div><div id="readingSubjects"></div><div id="readingBody"></div>';app.insertBefore(s,nav);let b=document.createElement('button');b.id='nreading';b.innerHTML='📖<br>Leitura';b.onclick=()=>{document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));mode(true);nav.querySelectorAll('button').forEach(x=>x.classList.remove('on'));s.classList.remove('hidden');b.classList.add('on');restore();window.scrollTo(0,0)};nav.insertBefore(b,nav.lastElementChild);nav.querySelectorAll('button:not(#nreading)').forEach(x=>x.addEventListener('click',()=>{s.classList.add('hidden');mode(false)}));return true}let n=0,t=setInterval(()=>{if(init()||++n>120)clearInterval(t)},50)})();