(function(){
let DATA=[],loaded=false;
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function natural(a,b){return String(a).localeCompare(String(b),'pt-BR',{numeric:true})}
async function load(){if(loaded)return true;const msg=document.getElementById('readingStatus');try{let r=await fetch('reading-data.json',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);let j=await r.json();if(!Array.isArray(j)||!j.length)throw new Error('vazio');DATA=j;loaded=true;if(msg)msg.textContent=DATA.length+' resumos carregados';renderSubjects();return true}catch(e){if(msg)msg.textContent='A base de leitura da Compilação Auditada V2 ainda está sendo preparada.';return false}}
function subjects(){return [...new Set(DATA.map(x=>x.subject))].sort(natural)}
function renderSubjects(){const box=document.getElementById('readingSubjects');if(!box)return;box.innerHTML='';subjects().forEach(s=>{let a=DATA.filter(x=>x.subject===s).sort((x,y)=>natural(x.lesson,y.lesson));let d=document.createElement('details');d.className='card readingSubject';d.innerHTML='<summary><b>'+esc(s)+'</b> <small>('+a.length+' aulas)</small></summary><div class="readingLessons"></div>';let l=d.querySelector('.readingLessons');a.forEach(x=>{let b=document.createElement('button');b.className='readingLesson';b.textContent=x.lesson;b.onclick=()=>show(x);l.appendChild(b)});box.appendChild(d)})}
function show(x){const v=document.getElementById('readingBody');if(!v)return;v.innerHTML='<div class="card"><small>'+esc(x.subject)+' • '+esc(x.lesson)+'</small><h2>'+esc(x.lesson)+'</h2><div class="readingSourceText">'+esc(x.text)+'</div></div>';localStorage.setItem('sefaz-hipotetico-reading-last-v1',JSON.stringify({subject:x.subject,lesson:x.lesson}));v.scrollIntoView({block:'start'})}
async function restore(){if(!await load())return;try{let p=JSON.parse(localStorage.getItem('sefaz-hipotetico-reading-last-v1')||'null');if(p){let x=DATA.find(z=>z.subject===p.subject&&z.lesson===p.lesson);if(x)show(x)}}catch(e){}}
function setReadingMode(on){document.body.classList.toggle('readingMode',!!on);document.getElementById('feedFilter')?.classList.toggle('hidden',!!on)}
function init(){if(document.getElementById('reading'))return true;const app=document.querySelector('.app'),nav=app&&app.querySelector('nav');if(!app||!nav)return false;const style=document.createElement('style');style.textContent='.readingSubject summary{cursor:pointer;padding:4px 0;font-size:17px}.readingLessons{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:10px}.readingLesson{padding:10px 7px;border:1px solid #24517c;border-radius:10px;background:#07182e;color:#fff;font-size:16px}.readingSourceText{white-space:pre-wrap;line-height:1.62;color:#e7eef7;font-size:18px}.readingSourceText::first-line{font-weight:700}body.readingMode #reading>p{font-size:16px;line-height:1.45}body.readingMode #feedFilter,body.readingMode .feedfilter,body.readingMode #cycleNavigator,body.readingMode #orderCycle,body.readingMode #orderRandom{display:none!important}body.readingMode #reading{padding-top:12px!important}@media(min-width:700px){.readingLessons{grid-template-columns:repeat(4,minmax(0,1fr))}.readingSourceText{font-size:19px}.readingSubject summary{font-size:18px}.readingLesson{font-size:17px}}';document.head.appendChild(style);const sec=document.createElement('section');sec.id='reading';sec.className='panel hidden';sec.innerHTML='<h2>📖 Leitura</h2><p>Conteúdo proveniente exclusivamente da Compilação SEFAZ-AL Auditada V2, organizado por matéria e aula.</p><div id="readingStatus" class="card">Carregando resumos...</div><div id="readingSubjects"></div><div id="readingBody"></div>';app.insertBefore(sec,nav);const b=document.createElement('button');b.id='nreading';b.innerHTML='📖<br>Leitura';b.onclick=function(){document.querySelectorAll('.app>main,.app>section').forEach(e=>e.classList.add('hidden'));setReadingMode(true);nav.querySelectorAll('button').forEach(x=>x.classList.remove('on'));sec.classList.remove('hidden');b.classList.add('on');restore();window.scrollTo(0,0)};nav.insertBefore(b,nav.lastElementChild);nav.querySelectorAll('button:not(#nreading)').forEach(x=>x.addEventListener('click',()=>{sec.classList.add('hidden');setReadingMode(false)}));return true}
let n=0,t=setInterval(()=>{n++;if(init()||n>120)clearInterval(t)},50);
})();